### ISSUE TITLE
Cannot assign retweeID

### ISSUE THREAD

**Issue by Kristofferkirk** [spences10/twitter-bot-bootstrap#87] opened 2017-08-16 19:22 UTC
I commented on a commit earlier but i'm sending in a issue instead:

Followed the setup instructions several times, but when im trying to start the bot i get the following error message:

"ERRORDERP: Cannot assign retweeID"

It is possible that it is the enviorment i use (C9 web based workspace). 

I tried as suggested changing LAN to LANGUAGE in the .env file but to no avail. Other suggested solutions are welcome.

**Comment by spences10** [comment] 2017-08-16 20:22
Oh, ok, in c9 what version of node are you on, 7+?

**Comment by mapk** [comment] 2017-08-17 01:09
I'm getting the same problem and on c9, I'm on node v8.2.1

**Comment by spences10** [comment] 2017-08-17 05:18
@Kristofferkirk and @mapk I have just pulled the `master` branch and had a look

My `.env` file is as follows:

```
TWITTER_CONSUMER_KEY=...
TWITTER_CONSUMER_SECRET=...
TWITTER_ACCESS_TOKEN=...-...
TWITTER_ACCESS_TOKEN_SECRET=...

QUERY_STRING=google,android
RANDOM_REPLY=Hi @${screenName} thanks for the follow! What are you working on today?,@${screenName} thanks for following! What are you working on today?,Hey @${screenName} thanks for the follow! What are you working on today?,Thanks for following @${screenName}! What are you working on today?,Thanks for following @${screenName}! What you uptp today?,Hey @${screenName}, working on anything code related today? Thanks for following,Awesome @${screenName}, thanks for following!,Thanks for the follow @${screenName}!,Thanks for the following @${screenName}! How are you today?

RESULT_TYPE=mixed
LANG=en

TWITTER_RETWEET_RATE=.1
TWITTER_SEARCH_COUNT=20
```

If I run `npm start` from the terminal I get output:

![image](https://user-images.githubusercontent.com/234708/29396873-96652b50-8312-11e7-8492-7d7b5bb17e89.png)

Changing the `,env` tag for language will resolve all languages being retweeted:

![image](https://user-images.githubusercontent.com/234708/29396947-0d0793ce-8313-11e7-9716-5aa4d7615dc0.png)

So that is incorrect and can be resolved with some documentation, the labels in the `.env` need to be the same as in the `config.js` file.

```javascript
  twitterConfig: {
    queryString: process.env.QUERY_STRING,
    resultType: process.env.RESULT_TYPE,
    language: process.env.LANGUAGE,
```

That is beside the point though and it still doesn't help you guys for this specific issue, do either of you want to share your c9 environments so I can take a look?

The only other thing I can think of that comes to mind is using 'use strict' in c9

**Comment by mapk** [comment] 2017-08-17 15:52
I can share my c9 with you. I tried the github email you have listed, but it says you're not a user.

**Comment by spences10** [comment] 2017-08-17 17:01
Should do, spences10 is my user on there

**Comment by spences10** [comment] 2017-08-18 06:44
Ok @mapk, I'm taking a look at your c9 instance, thank you

Is it the one keyword you want to search on?

It looks like it may be a limitation in my knowledge 😄 and a limitation in things for the bot to RT 😅 

It was erroring when trying to determine what status it to tweet it does this with `const rando = Math.floor(Math.random() * param.searchCount) + 1` it takes the search count from the `.env` file in this case 20 then returns a random number from that to use as the index of the `data` object for which tweet to RT

As there only seem to be on result for `Molokan` there's not a great deal for the bot to choose from 🙃 

In your c9 instance I didn't use `rando` in the end and just went with the first item in the object `[0]` 

If you take a look at your console when you get back to your c9 there's a fair bit of output on there where I'm `console.log(JSON.stringify(data))`ing out the `data` object just to clarify the bot was finding data.

This will need a bit of work so thanks for highlighting it 👌

**Comment by spences10** [comment] 2017-08-18 06:48
Ig you would like to interrogate the data yourselves you can take the output of `console.log(JSON.stringify(data))` and use something like [Awesome JSON](https://chrome.google.com/webstore/detail/json-viewer-awesome/iemadiahhbebdklepanmkjenfdebfpfe?utm_source=chrome-app-launcher-info-dialog) chrome extension to visualise the data.

It will transform this:

```
{"statuses":[{"created_at":"Fri Aug 18 06:34:17 +0000 2017","id":898432846653554700,"id_str":"898432846653554688","text":"RT @_hurican: I'm at Xəqani Bağı (Molokan Bağı) in Baku, Bakı https://t.co/ipCjQciXeX","truncated":false,"entities":{"hashtags":[],"symbols":[],"user_mentions":[{"screen_name":"_hurican","name":"Huri","id":808929329472278500,"id_str":"808929329472278528","indices":[3,12]}],"urls":[{"url":"https://t.co/ipCjQciXeX","expanded_url":"https://www.swarmapp.com/c/8zsxr6lcfuo","display_url":"swarmapp.com/c/8zsxr6lcfuo","indices":[62,85]}]},"metadata":{"result_type":"recent","iso_language_code":"tr"},"source":"<a href=\"https://mapk.github.io\" rel=\"nofollow\">molokan-bot</a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":897986449932402700,"id_str":"897986449932402688","name":"Molokan Bot","screen_name":"Molokan_bot","location":"","description":"","url":null,"entities":{"description":{"urls":[]}},"protected":false,"followers_count":0,"friends_count":0,"listed_count":0,"created_at":"Thu Aug 17 01:00:28 +0000 2017","favourites_count":0,"utc_offset":null,"time_zone":null,"geo_enabled":false,"verified":false,"statuses_count":1,"lang":"en","contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"F5F8FA","profile_background_image_url":null,"profile_background_image_url_https":null,"profile_background_tile":false,"profile_image_url":"http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png","profile_image_url_https":"https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png","profile_link_color":"1DA1F2","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"has_extended_profile":false,"default_profile":true,"default_profile_image":true,"following":false,"follow_request_sent":false,"notifications":false,"translator_type":"none"},"geo":null,"coordinates":null,"place":null,"contributors":null,"retweeted_status":{"created_at":"Fri Aug 11 12:30:03 +0000 2017","id":895985665569173500,"id_str":"895985665569173505","text":"I'm at Xəqani Bağı (Molokan Bağı) in Baku, Bakı https://t.co/ipCjQciXeX","truncated":false,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"https://t.co/ipCjQciXeX","expanded_url":"https://www.swarmapp.com/c/8zsxr6lcfuo","display_url":"swarmapp.com/c/8zsxr6lcfuo","indices":[48,71]}]},"metadata":{"result_type":"recent","iso_language_code":"tr"},"source":"<a href=\"http://foursquare.com\" rel=\"nofollow\">Foursquare</a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":808929329472278500,"id_str":"808929329472278528","name":"Huri","screen_name":"_hurican","location":"Azerbaijan ","description":"I'm a Supergirl","url":"https://t.co/vkBRKhXEA2","entities":{"url":{"urls":[{"url":"https://t.co/vkBRKhXEA2","expanded_url":"http://instagram.com/psixologram/","display_url":"instagram.com/psixologram/","indices":[0,23]}]},"description":{"urls":[]}},"protected":false,"followers_count":171,"friends_count":95,"listed_count":0,"created_at":"Wed Dec 14 06:59:16 +0000 2016","favourites_count":3823,"utc_offset":null,"time_zone":null,"geo_enabled":false,"verified":false,"statuses_count":461,"lang":"en","contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"000000","profile_background_image_url":"http://abs.twimg.com/images/themes/theme1/bg.png","profile_background_image_url_https":"https://abs.twimg.com/images/themes/theme1/bg.png","profile_background_tile":false,"profile_image_url":"http://pbs.twimg.com/profile_images/888677208029618176/cwTFqqKz_normal.jpg","profile_image_url_https":"https://pbs.twimg.com/profile_images/888677208029618176/cwTFqqKz_normal.jpg","profile_banner_url":"https://pbs.twimg.com/profile_banners/808929329472278528/1500582049","profile_link_color":"440000","profile_sidebar_border_color":"000000","profile_sidebar_fill_color":"000000","profile_text_color":"000000","profile_use_background_image":false,"has_extended_profile":true,"default_profile":false,"default_profile_image":false,"following":false,"follow_request_sent":false,"notifications":false,"translator_type":"none"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":1,"favorite_count":2,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"tr"},"is_quote_status":false,"retweet_count":1,"favorite_count":0,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"tr"},{"created_at":"Fri Aug 11 12:30:03 +0000 2017","id":895985665569173500,"id_str":"895985665569173505","text":"I'm at Xəqani Bağı (Molokan Bağı) in Baku, Bakı https://t.co/ipCjQciXeX","truncated":false,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"https://t.co/ipCjQciXeX","expanded_url":"https://www.swarmapp.com/c/8zsxr6lcfuo","display_url":"swarmapp.com/c/8zsxr6lcfuo","indices":[48,71]}]},"metadata":{"result_type":"recent","iso_language_code":"tr"},"source":"<a href=\"http://foursquare.com\" rel=\"nofollow\">Foursquare</a>","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":808929329472278500,"id_str":"808929329472278528","name":"Huri","screen_name":"_hurican","location":"Azerbaijan ","description":"I'm a Supergirl","url":"https://t.co/vkBRKhXEA2","entities":{"url":{"urls":[{"url":"https://t.co/vkBRKhXEA2","expanded_url":"http://instagram.com/psixologram/","display_url":"instagram.com/psixologram/","indices":[0,23]}]},"description":{"urls":[]}},"protected":false,"followers_count":171,"friends_count":95,"listed_count":0,"created_at":"Wed Dec 14 06:59:16 +0000 2016","favourites_count":3823,"utc_offset":null,"time_zone":null,"geo_enabled":false,"verified":false,"statuses_count":461,"lang":"en","contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"000000","profile_background_image_url":"http://abs.twimg.com/images/themes/theme1/bg.png","profile_background_image_url_https":"https://abs.twimg.com/images/themes/theme1/bg.png","profile_background_tile":false,"profile_image_url":"http://pbs.twimg.com/profile_images/888677208029618176/cwTFqqKz_normal.jpg","profile_image_url_https":"https://pbs.twimg.com/profile_images/888677208029618176/cwTFqqKz_normal.jpg","profile_banner_url":"https://pbs.twimg.com/profile_banners/808929329472278528/1500582049","profile_link_color":"440000","profile_sidebar_border_color":"000000","profile_sidebar_fill_color":"000000","profile_text_color":"000000","profile_use_background_image":false,"has_extended_profile":true,"default_profile":false,"default_profile_image":false,"following":false,"follow_request_sent":false,"notifications":false,"translator_type":"none"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":1,"favorite_count":2,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"tr"}],"search_metadata":{"completed_in":0.008,"max_id":898432846653554700,"max_id_str":"898432846653554688","query":"molokan+filter%3Asafe","refresh_url":"?since_id=898432846653554688&q=molokan%20filter%3Asafe&result_type=mixed&include_entities=1","count":20,"since_id":0,"since_id_str":"0"}}
```

To this:

![image](https://user-images.githubusercontent.com/234708/29447383-8c76d030-83e9-11e7-9159-45266f9d005d.png)

**Comment by mapk** [comment] 2017-08-18 18:09
So, could this not be resolved? I guess I'm just unclear on the next steps. Yes, I just wanted the bot to search for that one keyword, `molokan`. Thanks.

**Comment by spences10** [comment] 2017-08-18 18:17
It's due to the very small search results you get with the one search term @mapk because the random function, the random function was returning a number between 0-20 and the search results were only ever returning one result, meaning that it was very unlikely that the random number being picked would be 0 

So, what I'm trying to say is that the functionality currently doesn't work very well if there is a really small search criteria, I'll get round to fixing this eventually so that it picks a number from the length of the data object rather than the results number

What you could do, and what I'll be doing some time in the future with this bootstrap is use the Twitter stream function over the search function, this will immediately retweet anything that matches the search terms, would that be of interest?

**Comment by mapk** [comment] 2017-08-18 18:51
Yes, the solution around the Twitter stream seems like the way to go here.

**Comment by spences10** [comment] 2017-08-18 19:03
Ok @mapk can I ask you to take a look at [this](https://github.com/spences10/twitter-bot-twit) repo or maybe an even better one would be Wes Bos' [WesB0t](https://github.com/wesbos/wesbot)

IF you like I'll take a look at your c9 instance and try knock something up like it?

**Comment by mapk** [comment] 2017-08-18 19:14
@spences10 If you'd like to mess around in my c9 instance, that's cool. I'll take a look at those repos.

**Comment by mapk** [comment] 2017-08-18 19:17
Also, looks like the bot did post something recently. Maybe after you messed with it? If it works, I can start the process of moving it over to Heroku.

**Comment by spences10** [comment] 2017-08-18 19:26
I'd recommend using now from zeit.co 👍

**Comment by spences10** [comment] 2017-08-18 19:35
Ok `molokan`bot is up and running

**Comment by spences10** [comment] 2017-08-18 19:36
Set yourself up a `now` account @mapk and you're done

Follow the instructions for deploying to now from the README in this repo

Please let me know if you have any questions :+1

**Comment by mapk** [comment] 2017-08-18 19:37
Awesome, thanks. Can you document your changes that made this work for my particular c9?

**Comment by spences10** [comment] 2017-08-18 19:45
It uses the `.stream` function

Take a look here: https://github.com/spences10/twitter-bot-playground#use-twitter-stream-api

And also the Twitter-bot-twit repo which uses it exclusively 

I'll probably get round to documenting it all next release of this 👌

**Comment by spences10** [comment] 2017-08-18 19:46
@Kristofferkirk how about you?

**Comment by mapk** [comment] 2017-08-18 23:48
I tried deploying to Zeit and had another issue.

![screen shot 2017-08-18 at 4 47 39 pm](https://user-images.githubusercontent.com/617986/29481340-fb019b5c-8434-11e7-8bc6-a1df78170f4f.png)

**Comment by spences10** [comment] 2017-08-19 06:16
![image](https://user-images.githubusercontent.com/234708/29484031-edc3a5e2-84ad-11e7-8d27-68cda51e8a0d.png)

@mapk it looks like you're in the `twitter-bot-bootstrap` directory, if you come out and got into the `simple-stream-bot` directory and try again 👍 

```bash
mapk:~/workspace/twitter-bot-bootstrap (master) $ cd ..
mapk:~/workspace $ cd simp*
mapk:~/workspace/simple-stream-bot $ 
```

**Comment by Kristofferkirk** [comment] 2017-08-19 15:12
Im gonna try some more now

**Comment by spences10** [comment] 2017-08-28 11:25
@Kristofferkirk ok to close this now?

**Comment by benjammartin** [comment] 2017-09-02 15:35
I've the same problem on C9

**Comment by spences10** [comment] 2017-09-02 16:11
@benjammartin have you read the previous comments and understand why the issue may be caused?

**Comment by Kristofferkirk** [comment] 2017-09-04 05:20
Yeah it can be closed

**Comment by pabrams** [comment] 2017-09-05 06:06
Hi, I'm getting this same issue ("ERRORDERP: Cannot assign retweeID") on Cloud9.  I read the above, and I'm using more than just one search term.  Here's my query string:
QUERY_STRING=DevOps,Chess,PowerShell

**Comment by spences10** [comment] 2017-09-05 10:01
Hey @pabrams thanks for chiming in here, I have logged several issues to pick up when I return from holiday main one being to give some useful information on the errors.

If you find what's causing it in the meantime feel free to make a PR, would be greatly appreciated 👌

**Comment by pabrams** [comment] 2017-09-05 17:20
@spences10 Well, I didn't figure out what the problem was on C9, but I suspect it's something to do their security, so I went ahead and deployed the code anyway using zeit, and it seems to be working (one re-tweet so far).

**Comment by malithjkmt** [comment] 2017-09-07 02:51
I think there's a simple solution for this. 
The reason is, LANG, LANGUAGE... environment variable s in .env file are system reserved.
So, simply use a unique one.
I just changed it in .env and config.js, 
donezo!!!

more info.. -  https://help.ubuntu.com/community/EnvironmentVariables#The_LANGUAGE_priority_list

**Comment by DaveBryantLU** [comment] 2017-09-18 05:05
Any idea what would be causing "ERRORDERP: Cannot assign retweeID; exception message: Cannot read property 'id_str' of undefined" using the latest install method/guide?

**Comment by spences10** [comment] 2017-09-18 05:26
@pabrams I'm guessing `'use strict'`?

I didn't think it was an issue after switching no node 8

I'm beginning to wonder whether I should keep the c9 guide now, it's such a super quick way to have an environment though

**Comment by spences10** [comment] 2017-09-18 05:30
@DaveBryantLU it looks like it could be one of two things, but I'm not certain

Either the c9 environment, so if you could confirm if you're using c9 that would be handy

Or, the `LAN`, `KANGUAGE` issue mentioned earlier, try @malithjkmt's solution 

This issue has been closed so one of those two would be a good guess, if you find a fix please feel free to submit a PR here or to the https://github.com/spences10/twitter-bot-playground repo 👌

**Comment by DaveBryantLU** [comment] 2017-09-18 05:51
@malithjkmt's worked! :) 

Is there a way to limit the bot to only retweet specific accounts ? Like @Youtubegaming or @TwitterGaming for example ?

**Comment by spences10** [comment] 2017-09-18 05:58
@DaveBryantLU yes, you can add in some conditional logic to the RT event

I have something sort of done on another repo so you'll need to adapt it for your own purposes 

https://github.com/spences10/twitter-bot-twit/blob/master/src/helpers/dbHandleRetweet.js

So, set up your blacklist in your `.env` file then adapt the config file accordingly, feel free to submit a PR if you get something working, could be a good addition to the bootstrap

Thanks

**Closed** 2017-09-18 05:58 UTC
Labels: bug, in progress

**Comment by ibeckermayer** [comment] 2017-10-24 05:22
I am getting this same error on c9, despite the language variable fix.

`ʕʘ̅͜ʘ̅ʔ ERRORDERP: Cannot assign retweeID; exception message: Cannot read property 'id_str' of undefined`

Any idea what could be causing it. I followed the instructions exactly as in your tutorial (https://github.com/spences10/twitter-bot-bootstrap). I am trying to deploy to ZEIT now to see if it's c9 that's causing the issue.

**Comment by spences10** [comment] 2017-10-24 05:28
Do you mind emailing me a link to your c9 instance @ibeckermayer, so I can take a look?

**Comment by ibeckermayer** [comment] 2017-10-24 05:32
Sure. I've figured out that data.statuses.length is returning 0, so I must not be receiving anything back from my query. One second while I figure out how to link you to the instance (I'm new to c9)

**Comment by ibeckermayer** [comment] 2017-10-24 05:34
There you are @spences10

**Comment by spences10** [comment] 2017-10-24 05:35
Well, if `data.statuses.length` is returning 0 then that may be the cause, I was under the impression that for zero length `data.statuses` the code failed gracefully.

**Comment by ibeckermayer** [comment] 2017-10-24 05:38
Do you have any understanding of why this may be happening. I've set up my .env so that QUERY_STRING=#careersinsoftware, which returns a few tweets if I put it in the Twitter search bar. Am I missing something obvious here?

**Comment by ibeckermayer** [comment] 2017-10-24 06:46
Update: Scott helped determine that the issue was related the data coming in from single string queries and he's working on a fix/update. If you need the fix immediately (before he's updated the repo), feel free to contact me about it.

**Comment by spences10** [comment] 2017-10-24 09:24
So, I think @pabrams did a bit of work on the `data.length` to fail gracefully if there were no results from the search but it's still an issue.

If you want a bot to be very focused and specific, for one keyword to retweet on then I'm not sure that using search is the best way to do it and in place of that use the Twitter stream API for such things
